set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affENZTRUEVSFALSE.png'
plot './ergebnisse/PgegenLmit0C7Vtrueenz20aff0attfalsemetro' with lines title 'C0 Aff20 Att0 Metrofalse', './ergebnisse/PgegenLmit10C7Vtrueenz20aff0attfalsemetro' with lines title 'C10 Aff20 Att0 Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Metrofalse', './ergebnisse/PgegenLmit0C7Vfalseenz20aff0attfalsemetro' with lines title 'C0 Aff20 Att0 Metrofalse', './ergebnisse/PgegenLmit10C7Vfalseenz20aff0attfalsemetro' with lines title 'C10 Aff20 Att0 Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL50affENZTRUEVSFALSE.png'
plot './ergebnisse/PgegenLmit0C7Vtrueenz50aff0attfalsemetro' with lines title 'C0 Aff50 Att0 Metrofalse', './ergebnisse/PgegenLmit10C7Vtrueenz50aff0attfalsemetro' with lines title 'C10 Aff50 Att0 Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz50aff0attfalsemetro' with lines title 'C30 Aff50 Att0 Metrofalse', './ergebnisse/PgegenLmit0C7Vfalseenz50aff0attfalsemetro' with lines title 'C0 Aff50 Att0 Metrofalse', './ergebnisse/PgegenLmit10C7Vfalseenz50aff0attfalsemetro' with lines title 'C10 Aff50 Att0 Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz50aff0attfalsemetro' with lines title 'C30 Aff50 Att0 Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affENZTRUEVSFALSE.png'
plot './ergebnisse/PgegenLmit0C7Vtrueenz20aff0attfalsemetro' with lines title 'C0 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit10C7Vtrueenz20aff0attfalsemetro' with lines title 'C10 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit0C7Vfalseenz20aff0attfalsemetro' with lines title 'C0 Aff20 Att0 Enzfalse Metrofalse', './ergebnisse/PgegenLmit10C7Vfalseenz20aff0attfalsemetro' with lines title 'C10 Aff20 Att0 Enzfalse Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enzfalse Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL50affENZTRUEVSFALSE.png'
plot './ergebnisse/PgegenLmit0C7Vtrueenz50aff0attfalsemetro' with lines title 'C0 Aff50 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit10C7Vtrueenz50aff0attfalsemetro' with lines title 'C10 Aff50 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz50aff0attfalsemetro' with lines title 'C30 Aff50 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit0C7Vfalseenz50aff0attfalsemetro' with lines title 'C0 Aff50 Att0 Enzfalse Metrofalse', './ergebnisse/PgegenLmit10C7Vfalseenz50aff0attfalsemetro' with lines title 'C10 Aff50 Att0 Enzfalse Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz50aff0attfalsemetro' with lines title 'C30 Aff50 Att0 Enzfalse Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enzfalse Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enzfalse Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vfalseenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enzfalse Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff2attfalsemetro' with lines title 'C30 Aff20 Att2 Enztrue Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.5attfalsemetro' with lines title 'C30 Aff20 Att0.5 Enztrue Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.5attfalsemetro' with lines title 'C30 Aff20 Att0.5 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.8attfalsemetro' with lines title 'C30 Aff20 Att0.8 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.5attfalsemetro' with lines title 'C30 Aff20 Att0.5 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.8attfalsemetro' with lines title 'C30 Aff20 Att0.8 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse'
set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL20affWechselwirkungen.png'
plot './ergebnisse/PgegenLmit30C7Vtrueenz20aff0attfalsemetro' with lines title 'C30 Aff20 Att0 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.01attfalsemetro' with lines title 'C30 Aff20 Att0.01 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.1attfalsemetro' with lines title 'C30 Aff20 Att0.1 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.5attfalsemetro' with lines title 'C30 Aff20 Att0.5 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff0.8attfalsemetro' with lines title 'C30 Aff20 Att0.8 Enztrue Metrofalse', './ergebnisse/PgegenLmit30C7Vtrueenz20aff1attfalsemetro' with lines title 'C30 Aff20 Att1 Enztrue Metrofalse'
