set terminal png
set xlabel 'Ligandenanteil in \%'
set ylabel "Bindewahrscheinlichkeit"
set output './ergebnisse/PlotPgegenL60aff.png'
plot './ergebnisse/PgegenLmit0C6falseenz60aff' with lines title 'C0 Aff60', './ergebnisse/PgegenLmit10C6falseenz60aff' with lines title 'C10 Aff60', './ergebnisse/PgegenLmit20C6falseenz60aff' with lines title 'C20 Aff60', './ergebnisse/PgegenLmit30C6falseenz60aff' with lines title 'C30 Aff60', './ergebnisse/PgegenLmit40C6falseenz60aff' with lines title 'C40 Aff60', './ergebnisse/PgegenLmit50C6falseenz60aff' with lines title 'C50 Aff60', './ergebnisse/PgegenLmit60C6falseenz60aff' with lines title 'C60 Aff60', 
